name: Theme Check
on:
  pull_request:
    branches: ["main", "staging"]
  push:
    branches: ["main", "staging"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: gem install theme-check
      - run: theme-check
